schema_version: 1

context:
  name: yt-dlp-ejs
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/yt_dlp_ejs-${{ version }}.tar.gz
  sha256: 8dfae59e418232f485253dcf8e197fefa232423c3af7824fe19e4517b173293b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - deno
  host:
    - python ${{ python_min }}*
    - hatchling >=1.27.0
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - yt-dlp #not an actual dependancies, but is useless without it

tests:
  - python:
      imports:
        - yt_dlp_ejs
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: External JavaScript for yt-dlp supporting many runtimes
  license: Unlicense
  license_file: LICENSE
  repository: https://github.com/yt-dlp/ejs
  homepage: https://github.com/yt-dlp/ejs
  documentation: https://github.com/yt-dlp/yt-dlp/wiki/EJS

extra:
  recipe-maintainers:
    - HeavyTony2
